import { projectMobileNotes, type MobileNote, type MobileNoteSource } from './mobileNoteProjection'
import { createFixtureMobileVaultRepository } from './mobileVaultRepository'

export type { MobileNote } from './mobileNoteProjection'

export const demoNoteSources: MobileNoteSource[] = [
  {
    archived: false,
    belongsTo: ['Tolaria MVP'],
    has: ['workflow-orchestration-checklist'],
    id: 'workflow',
    type: 'Essay',
    icon: 'pen-nib',
    date: 'May 13, 2026',
    modified: '6h ago',
    filename: 'workflow.md',
    relatedTo: ['release', 'mobile-roadmap'],
    tags: ['Design Inspiration', 'Tolaria MVP'],
    content: [
      '---',
      'title: Workflow Orchestration Essay',
      'type: Essay',
      'status: Draft',
      'tags: [Design Inspiration, Tolaria MVP]',
      'belongs_to: [Tolaria MVP]',
      'related_to: [release, mobile-roadmap]',
      'has: [workflow-orchestration-checklist]',
      '---',
      '',
      '# Workflow Orchestration Essay',
      '',
      '- The current narrative / temptation: everything routed through an LLM.',
      '- A real example (Tolaria + OpenClaw): OpenClaw does a lot for me in product development.',
      '- The cost of AI everywhere: expensive, slow, and unpredictable.',
      '- Where orchestration wins: observability, human-in-the-loop approvals, reliability.',
      '',
      'This connects to [[mobile-roadmap|the mobile roadmap]] and the [[workflow-orchestration-checklist]].',
    ].join('\n'),
  },
  {
    archived: false,
    belongsTo: ['Tolaria MVP'],
    has: ['workflow'],
    id: 'mobile-roadmap',
    type: 'Project',
    icon: 'wrench',
    date: 'May 5, 2026',
    modified: '1h ago',
    filename: 'mobile-roadmap.md',
    relatedTo: ['release'],
    tags: ['Tolaria MVP', 'mobile'],
    content: [
      '---',
      'title: Mobile Roadmap',
      'type: Project',
      'status: Active',
      'tags: [Tolaria MVP, mobile]',
      'belongs_to: [Tolaria MVP]',
      'related_to: [release]',
      'has: [workflow]',
      '---',
      '',
      '# Mobile Roadmap',
      '',
      'Local-first workflow parity comes before cloud sync.',
      '',
      '- Sidebar navigation by type',
      '- Raw editor for direct markdown edits',
      '- Wikilinks like [[workflow]] and [[release]]',
    ].join('\n'),
  },
  {
    archived: false,
    belongsTo: ['workflow'],
    has: [],
    id: 'workflow-orchestration-checklist',
    type: 'Note',
    icon: 'file-text',
    date: 'May 5, 2026',
    modified: '2h ago',
    filename: 'workflow-orchestration-checklist.md',
    relatedTo: ['workflow'],
    tags: ['mobile'],
    content: [
      '---',
      'title: Workflow Orchestration Checklist',
      'type: Note',
      'status: Draft',
      'tags: [mobile]',
      'belongs_to: [workflow]',
      'related_to: [workflow]',
      '---',
      '',
      '# Workflow Orchestration Checklist',
      '',
      '- Validate breadcrumbs',
      '- Validate [[workflow]] wikilinks',
      '- Validate relationships panel',
    ].join('\n'),
  },
  {
    archived: false,
    belongsTo: ['Tolaria MVP'],
    has: [],
    id: 'release',
    type: 'Release Note',
    icon: 'flag',
    date: 'May 2, 2026',
    modified: '12h ago',
    filename: 'release.md',
    relatedTo: ['workflow', 'mobile-roadmap'],
    tags: ['Release', 'Stable'],
    content: [
      '---',
      'title: v2026-05-02',
      'type: Release Note',
      'status: Done',
      'tags: [Release, Stable]',
      'belongs_to: [Tolaria MVP]',
      'related_to: [workflow, mobile-roadmap]',
      '---',
      '',
      '# v2026-05-02',
      '',
      'Another Tolaria release in the bag. This one is focused on performance, bug fixes, and lower-friction note workflows.',
      '',
      'Follow-up work lives in [[mobile-roadmap]].',
    ].join('\n'),
  },
  {
    archived: false,
    belongsTo: ['Tolaria MVP'],
    has: ['resources'],
    id: 'migration',
    type: 'Project',
    icon: 'git-branch',
    date: 'Apr 28, 2026',
    modified: '1d ago',
    filename: 'migration.md',
    relatedTo: ['mobile-roadmap'],
    tags: ['Project', 'Resources'],
    content: [
      '---',
      'title: Tolaria <> Obsidian migration proposal',
      'type: Project',
      'status: Active',
      'tags: [Project, Resources]',
      'belongs_to: [Tolaria MVP]',
      'related_to: [mobile-roadmap]',
      'has: [resources]',
      '---',
      '',
      '# Tolaria <> Obsidian migration proposal',
      '',
      'Obsidian vaults are already close to Tolaria ideal substrate: local Markdown, portable attachments, and git-backed history.',
    ].join('\n'),
  },
  {
    archived: false,
    belongsTo: ['migration'],
    has: [],
    id: 'resources',
    type: 'Resource',
    icon: 'books',
    date: 'Apr 20, 2026',
    modified: '3d ago',
    filename: 'resources.md',
    relatedTo: ['migration', 'mobile-roadmap'],
    tags: ['Resources', 'mobile'],
    content: [
      '---',
      'title: Mobile Resources',
      'type: Resource',
      'status: Active',
      'tags: [Resources, mobile]',
      'belongs_to: [migration]',
      'related_to: [migration, mobile-roadmap]',
      '---',
      '',
      '# Mobile Resources',
      '',
      'References for [[mobile-roadmap]] and local vault workflow QA.',
    ].join('\n'),
  },
  {
    archived: true,
    belongsTo: [],
    has: [],
    id: 'old-mobile-spike',
    type: 'Note',
    icon: 'archive',
    date: 'Mar 30, 2026',
    modified: 'last month',
    filename: 'old-mobile-spike.md',
    relatedTo: ['mobile-roadmap'],
    tags: ['mobile'],
    content: [
      '---',
      'title: Old Mobile Spike',
      'type: Note',
      'archived: true',
      'tags: [mobile]',
      'related_to: [mobile-roadmap]',
      '---',
      '',
      '# Old Mobile Spike',
      '',
      'Archived prototype notes kept around for comparison with [[mobile-roadmap]].',
    ].join('\n'),
  },
]

export const notes: MobileNote[] = projectMobileNotes(demoNoteSources)

export const demoVaultRepository = createFixtureMobileVaultRepository(demoNoteSources)
