export const desktopParityColors = {
  accentBlue: '#155DFF',
  accentBlueLight: '#155DFF14',
  accentGreen: '#38A169',
  accentGreenLight: 'rgba(56, 161, 105, 0.1)',
  accentOrange: '#D9730D',
  accentOrangeLight: 'rgba(217, 115, 13, 0.1)',
  accentPurple: '#805AD5',
  accentPurpleLight: 'rgba(128, 90, 213, 0.1)',
  accentRed: '#E53E3E',
  accentRedLight: 'rgba(229, 62, 62, 0.1)',
  accentYellow: '#D69E2E',
  accentYellowLight: 'rgba(214, 158, 46, 0.1)',
  borderDefault: '#E9E9E7',
  borderStrong: '#D9D9D6',
  stateHover: '#EBEBEA',
  stateHoverSubtle: '#F0F0EF',
  stateSelected: '#E8F4FE',
  stateSelectedStrong: '#D8ECFE',
  surfaceApp: '#FFFFFF',
  surfaceButton: '#EBEBEA',
  surfaceCard: '#FFFFFF',
  surfaceEditor: '#FFFFFF',
  surfaceSidebar: '#F7F6F3',
  textFaint: '#B4B4B4',
  textInverse: '#FFFFFF',
  textPrimary: '#37352F',
  textSecondary: '#787774',
} as const

export const desktopSidebarParity = {
  countPillHeight: 20,
  countPillMinWidth: 22,
  countPillPaddingHorizontal: 6,
  countPillRadius: 999,
  countPillTextSize: 10,
  folderIconGap: 8,
  folderIconSize: 17,
  folderRowContentInset: 12,
  folderRowIndent: 25,
  groupHeaderPadding: {
    regular: { bottom: 8, left: 12, right: 14, top: 8 },
    withCount: { bottom: 8, left: 12, right: 8, top: 8 },
  },
  itemGap: 8,
  itemIconSize: 16,
  itemPadding: {
    regular: { bottom: 6, left: 12, right: 16, top: 6 },
    withCount: { bottom: 6, left: 12, right: 8, top: 6 },
  },
  itemRadius: 4,
  itemTextSize: 13,
  sectionContentPaddingBottom: 8,
  sectionHorizontalPadding: 6,
  titleBarHeight: 52,
  topNavPadding: { bottom: 4, left: 6, right: 6, top: 4 },
} as const

export const desktopNoteItemParity = {
  borderLeftWidth: 3,
  contentGap: 8,
  iconInsetRight: 12,
  iconInsetTop: 10,
  iconSize: 14,
  padding: { bottom: 14, left: 16, right: 16, top: 14 },
  selectedPaddingLeft: 13,
  snippetLineHeight: 18,
  snippetTextSize: 12,
  titleLineHeight: 18,
  titleTextSize: 13,
} as const

export const desktopPropertyParity = {
  chipHeight: 24,
  chipPaddingHorizontal: 8,
  chipRadius: 6,
  chipTextSize: 12,
  labelIconSlot: 20,
  labelTextSize: 12,
  panelPadding: 12,
  rowMinHeight: 28,
  rowPaddingHorizontal: 6,
} as const

export const desktopEditorParity = {
  bodyFontSize: 15,
  bodyLineHeight: 23,
  contentMaxWidth: 720,
  contentPaddingHorizontal: 40,
  contentPaddingVertical: 20,
  h1FontSize: 32,
  h1LineHeight: 38,
  h1MarginBottom: 12,
  h1PaddingBottom: 16,
  h2FontSize: 27,
  h2LineHeight: 38,
  h2MarginBottom: 10,
  h2MarginTop: 28,
  h3FontSize: 20,
  h3LineHeight: 28,
  h3MarginBottom: 8,
  h3MarginTop: 24,
  listBulletGap: 6,
  listBulletSize: 24,
  listIndentSize: 24,
  paragraphSpacing: 8,
  quoteMarginVertical: 12,
  quotePaddingLeft: 16,
  tableCellPaddingHorizontal: 12,
  tableCellPaddingVertical: 8,
  tableFontSize: 14,
} as const

export const desktopPanelParity = {
  inspectorWidth: 300,
  noteListWidth: 340,
  sidebarWidth: 260,
  toolbarHeight: 52,
} as const
