export type MobileParityInventoryEntry = {
  assertions: string[]
  contracts: string[]
  desktopSource: string
  mobileFile: string
  surface: string
}

export const mobileParityInventory = [
  {
    assertions: ['panel chrome computed styles'],
    contracts: ['desktopPanelParity', 'desktopToolbarParity'],
    desktopSource: 'App shell split panes, NoteListHeader, InspectorHeader, BreadcrumbBar',
    mobileFile: 'src/ui/MobilePanel.tsx',
    surface: 'Panel and toolbar chrome',
  },
  {
    assertions: ['sync footer computed styles'],
    contracts: ['desktopStatusBarParity'],
    desktopSource: 'StatusBarFooter and StatusBarAction',
    mobileFile: 'src/ui/MobileButton.tsx',
    surface: 'Status-density buttons',
  },
  {
    assertions: ['action-sheet input computed styles through user-flow checks'],
    contracts: ['desktopPropertyParity'],
    desktopSource: 'shadcn Input wrappers used by desktop dialogs and property editors',
    mobileFile: 'src/ui/MobileTextInput.tsx',
    surface: 'Mobile text inputs',
  },
  {
    assertions: ['property chips and sidebar count computed styles'],
    contracts: ['desktopPropertyParity', 'desktopSidebarParity'],
    desktopSource: 'SidebarCountPill and property chip styles',
    mobileFile: 'src/ui/MobileChip.tsx',
    surface: 'Pills and property chips',
  },
  {
    assertions: ['toolbar action computed styles'],
    contracts: ['desktopToolbarActionParity'],
    desktopSource: 'NoteListHeader action buttons and BreadcrumbBar icon buttons',
    mobileFile: 'src/ui/MobileIconButton.tsx',
    surface: 'Toolbar icon actions',
  },
  {
    assertions: ['note list computed styles'],
    contracts: ['desktopNoteItemParity'],
    desktopSource: 'NoteItem',
    mobileFile: 'src/ui/MobileListRow.tsx',
    surface: 'Note list rows',
  },
  {
    assertions: ['properties computed styles'],
    contracts: ['desktopPropertyParity'],
    desktopSource: 'propertyPanelLayout',
    mobileFile: 'src/ui/MobilePropertyRow.tsx',
    surface: 'Property rows',
  },
  {
    assertions: ['sidebar computed styles and click navigation'],
    contracts: ['desktopPanelParity', 'desktopSidebarParity'],
    desktopSource: 'SidebarGroupHeader, SidebarParts, FolderTree',
    mobileFile: 'src/components/workspace/MobileWorkspaceSidebar.tsx',
    surface: 'Workspace sidebar',
  },
  {
    assertions: ['sidebar folder computed styles, measured native row insets, and click navigation'],
    contracts: ['desktopSidebarParity'],
    desktopSource: 'FolderTree',
    mobileFile: 'src/components/workspace/MobileWorkspaceSidebarFolderTree.tsx',
    surface: 'Workspace sidebar folder tree',
  },
  {
    assertions: ['sidebar count computed styles'],
    contracts: ['desktopSidebarParity'],
    desktopSource: 'SidebarCountPill',
    mobileFile: 'src/components/workspace/MobileSidebarCountPill.tsx',
    surface: 'Sidebar note counts',
  },
  {
    assertions: ['note list computed styles and selection click'],
    contracts: ['desktopNoteItemParity', 'desktopPanelParity', 'desktopToolbarParity'],
    desktopSource: 'NoteListHeader and NoteItem',
    mobileFile: 'src/components/workspace/MobileNoteListPanel.tsx',
    surface: 'Note list panel',
  },
  {
    assertions: ['note-list bulk-selection user-flow checks'],
    contracts: ['desktopNoteItemParity'],
    desktopSource: 'BulkActionBar and NoteList multi-select actions',
    mobileFile: 'src/components/workspace/MobileNoteListBulkActionBar.tsx',
    surface: 'Note-list bulk action bar',
  },
  {
    assertions: ['properties computed styles', 'derived reference groups from inspector semantics'],
    contracts: ['desktopPanelParity', 'desktopPropertyParity', 'desktopRelationshipParity'],
    desktopSource: 'InspectorHeader, propertyPanelLayout, RelationshipsPanel, InstancesPanel, ReferencedByPanel, BacklinksPanel',
    mobileFile: 'src/components/workspace/MobilePropertiesPanel.tsx',
    surface: 'Properties panel',
  },
  {
    assertions: ['sync footer computed styles'],
    contracts: ['desktopStatusBarParity'],
    desktopSource: 'StatusBarFooter and StatusBarBadges',
    mobileFile: 'src/components/workspace/MobileSyncStatusBar.tsx',
    surface: 'Sync status bar',
  },
  {
    assertions: ['note and relationship icon size/color computed through parent rows'],
    contracts: ['desktopNoteItemParity', 'desktopRelationshipParity'],
    desktopSource: 'NoteItem type indicators and inspector relationship icons',
    mobileFile: 'src/components/workspace/MobileWorkspaceIcons.tsx',
    surface: 'Workspace type icons',
  },
  {
    assertions: ['search/create/properties/more user-flow checks', 'source-backed tldraw whiteboard metadata and snapshot edit checks'],
    contracts: ['desktopPanelParity', 'desktopPropertyParity', 'desktopToolbarActionParity'],
    desktopSource: 'Desktop command dialogs, note-list search, inspector property forms, and tldraw fenced markdown persistence',
    mobileFile: 'src/components/workspace/MobileWorkspaceActionSheet.tsx',
    surface: 'Read-only workspace action sheets',
  },
  {
    assertions: ['note-more action user-flow checks', 'source-backed markdown table and tldraw edit checks'],
    contracts: ['desktopPanelParity', 'desktopToolbarActionParity'],
    desktopSource: 'Desktop note context menu, BreadcrumbBar note actions, editor command actions, markdown tables, and tldraw fenced markdown persistence',
    mobileFile: 'src/components/workspace/MobileWorkspaceMoreActionsContent.tsx',
    surface: 'Workspace More actions content',
  },
  {
    assertions: ['note-more action user-flow checks'],
    contracts: ['desktopPanelParity', 'desktopToolbarActionParity'],
    desktopSource: 'Desktop note context menu, BreadcrumbBar note actions, and editor command actions',
    mobileFile: 'src/components/workspace/MobileNoteMoreActions.tsx',
    surface: 'Note more actions',
  },
  {
    assertions: ['source-backed markdown table resize and cell edit checks'],
    contracts: ['desktopEditorParity', 'desktopToolbarActionParity'],
    desktopSource: 'BlockNote table editing, markdown table serialization, and editor command actions',
    mobileFile: 'src/components/workspace/MobileTableMoreActions.tsx',
    surface: 'Table more actions',
  },
  {
    assertions: ['source-backed code, math, and Mermaid block edit checks'],
    contracts: ['desktopEditorParity', 'desktopToolbarActionParity'],
    desktopSource: 'BlockNote code blocks, math markdown, Mermaid fences, and editor command actions',
    mobileFile: 'src/components/workspace/MobileSourceBlockMoreActions.tsx',
    surface: 'Source block more actions',
  },
  {
    assertions: ['source-backed tldraw whiteboard metadata and snapshot edit checks'],
    contracts: ['desktopEditorParity', 'desktopToolbarActionParity'],
    desktopSource: 'Desktop tldraw fenced markdown persistence and editor command actions',
    mobileFile: 'src/components/workspace/MobileWhiteboardMoreActions.tsx',
    surface: 'Whiteboard more actions',
  },
  {
    assertions: ['editor find/replace unit tests', 'editor find/replace user-flow checks'],
    contracts: ['desktopEditorParity', 'desktopToolbarActionParity'],
    desktopSource: 'RawEditorFindBar and shared editorFind utilities',
    mobileFile: 'src/components/workspace/MobileEditorFindSheet.tsx',
    surface: 'Editor find and replace sheet',
  },
  {
    assertions: ['mobile table-of-contents model tests', 'phone More-menu table-of-contents user-flow checks'],
    contracts: ['desktopEditorParity', 'desktopToolbarActionParity'],
    desktopSource: 'TableOfContentsPanel and tableOfContentsModel',
    mobileFile: 'src/components/workspace/MobileTableOfContentsSheet.tsx',
    surface: 'Editor table of contents sheet',
  },
  {
    assertions: ['saved-view reorder user-flow checks', 'type-section reorder user-flow checks'],
    contracts: ['desktopSidebarParity', 'desktopToolbarActionParity'],
    desktopSource: 'Sidebar saved-view and type-section context actions',
    mobileFile: 'src/components/workspace/MobileWorkspaceMoveActions.tsx',
    surface: 'Workspace sidebar reorder actions',
  },
  {
    assertions: ['typed property edit user-flow checks'],
    contracts: ['desktopPropertyParity'],
    desktopSource: 'Inspector property editors and shadcn segmented button controls',
    mobileFile: 'src/components/workspace/MobilePropertyValueKindPicker.tsx',
    surface: 'Property value kind picker',
  },
  {
    assertions: ['typed property edit user-flow checks for status, date, URL, and color values'],
    contracts: ['desktopPropertyParity'],
    desktopSource: 'PropertyValueCells.tsx and DynamicPropertiesPanel type-aware add property form',
    mobileFile: 'src/components/workspace/MobilePropertyValueEditor.tsx',
    surface: 'Typed property value editor',
  },
  {
    assertions: ['property and relationship suggestion user-flow checks', 'relationship target and Type-defined view-value resolution parity'],
    contracts: ['desktopPropertyParity'],
    desktopSource: 'RelationshipsPanel note search dropdown and inspector property forms',
    mobileFile: 'src/components/workspace/MobileWorkspaceSuggestionList.tsx',
    surface: 'Workspace action-sheet suggestions',
  },
  {
    assertions: ['saved-view filter edit user-flow checks'],
    contracts: ['desktopPropertyParity'],
    desktopSource: 'FilterBuilder, FilterFieldCombobox, shadcn inputs and buttons',
    mobileFile: 'src/components/workspace/MobileViewFilterBuilder.tsx',
    surface: 'Saved-view filter builder',
  },
  {
    assertions: ['saved-view column edit user-flow checks'],
    contracts: ['desktopPropertyParity'],
    desktopSource: 'ListPropertiesPopover and NoteListHeader column customization',
    mobileFile: 'src/components/workspace/MobileViewDisplayPropertiesPicker.tsx',
    surface: 'Saved-view note-list column picker',
  },
  {
    assertions: ['saved-view sort user-flow checks', 'type-section sort user-flow checks'],
    contracts: ['desktopPropertyParity', 'desktopToolbarActionParity'],
    desktopSource: 'SortDropdown and NoteListHeader sort persistence',
    mobileFile: 'src/components/workspace/MobileSortPicker.tsx',
    surface: 'Saved-view and Type-section sort picker',
  },
  {
    assertions: ['saved-view metadata user-flow checks', 'type-section metadata user-flow checks'],
    contracts: ['desktopPropertyParity', 'desktopSidebarParity'],
    desktopSource: 'CustomizeTypeDialog, CreateViewDialog, and sidebar icon/color metadata',
    mobileFile: 'src/components/workspace/MobileMetadataPicker.tsx',
    surface: 'Saved-view and Type-section metadata picker',
  },
  {
    assertions: ['type-section edit user-flow checks', 'type schema/default edit user-flow checks'],
    contracts: ['desktopPropertyParity', 'desktopSidebarParity'],
    desktopSource: 'TypeCustomizePopover, Type document frontmatter schema/defaults, Sidebar type context actions, and NoteListHeader type columns',
    mobileFile: 'src/components/workspace/MobileTypeSectionEditor.tsx',
    surface: 'Type section editor',
  },
  {
    assertions: ['phone type-section visibility user-flow checks', 'Type visibility reducer regression tests'],
    contracts: ['desktopSidebarParity', 'desktopPropertyParity'],
    desktopSource: 'SidebarParts VisibilityPopover and Type document visible frontmatter',
    mobileFile: 'src/components/workspace/MobileTypeVisibilityEditor.tsx',
    surface: 'Type section visibility editor',
  },
  {
    assertions: ['markdown formatting command user-flow checks for paste without formatting, inline marks, H1-H6 headings, lists, blocks, wikilinks, tables, math, Mermaid, and whiteboards', 'native iOS WYSIWYG markdown block insertion proof'],
    contracts: ['desktopToolbarActionParity'],
    desktopSource: 'BlockNote formatting commands and BreadcrumbBar icon button sizing',
    mobileFile: 'src/components/workspace/MobileMarkdownFormattingToolbar.tsx',
    surface: 'Markdown formatting toolbar',
  },
  {
    assertions: ['TenTap native simulator rendering', 'native WYSIWYG layout metric contract', 'native WYSIWYG rich bridge mutation/save proof for inline marks, wikilinks, lists, quotes, code fences, horizontal rules, H1, and table-source lines', 'native WYSIWYG Expo FileSystem persistence proof', 'native WYSIWYG formatting command mapping tests for H1-H6 headings and supported rich commands', 'native WYSIWYG input-transform tests for desktop arrow ligatures, escaped arrow literals, and completed highlight syntax', 'native WYSIWYG full-document save serialization tests', 'Tolaria-owned native formatting toolbar for supported rich commands', 'document-content hydration and serialization with raw frontmatter, desktop highlight, escaped inline markdown punctuation, wikilink alias/no-alias, angle-wrapped attachment links, URL/email autolinks, bare URL/email save preservation, image titles, remote image URLs with balanced parentheses, inline image source paragraphs, empty headings, empty list items, mixed nested list kinds, list continuation and list hard-break source blocks, non-1 ordered list starts, ordered-paren and repeated-marker source lists, blank blockquotes, display math, hard-break, blockquote paragraphs, unsupported-table, details/html-comment blocks, root image, and indented image/heading/list/code-fence/display-math/text source regression checks'],
    contracts: ['desktopEditorParity', 'desktopToolbarActionParity'],
    desktopSource: 'EditorTheme.css, theme.json, BlockNote/Tiptap document editing, richEditorInputTransformExtension, and desktop markdown serialization',
    mobileFile: 'src/components/workspace/MobileWysiwygMarkdownEditor.native.tsx',
    surface: 'Native WYSIWYG document editor',
  },
  {
    assertions: ['WYSIWYG wikilink picker suggestion tests', 'native iOS WYSIWYG wikilink insertion proof'],
    contracts: ['desktopEditorParity', 'desktopToolbarActionParity'],
    desktopSource: 'BlockNote wikilink suggestion menu and shared wikilink autocomplete candidates',
    mobileFile: 'src/components/workspace/MobileWysiwygWikilinkPicker.tsx',
    surface: 'Native WYSIWYG wikilink picker',
  },
  {
    assertions: ['single document source edit user-flow checks', 'native source selection preservation proof', 'wikilink and person autocomplete user-flow checks'],
    contracts: ['desktopEditorParity', 'desktopToolbarActionParity'],
    desktopSource: 'RawEditorView, BlockNote markdown commands, and editor wikilink/person suggestion menus',
    mobileFile: 'src/components/workspace/MobileMarkdownSourceEditor.tsx',
    surface: 'Markdown source document editor',
  },
  {
    assertions: ['web fallback keeps source-editor user-flow coverage available'],
    contracts: ['desktopEditorParity', 'desktopToolbarActionParity'],
    desktopSource: 'BlockNote/Tiptap document editing with RawEditorView fallback',
    mobileFile: 'src/components/workspace/MobileWysiwygMarkdownEditor.tsx',
    surface: 'Web fallback document editor',
  },
  {
    assertions: ['editor computed styles', 'markdown block parser regression checks', 'wikilink tap target resolution parity'],
    contracts: ['desktopEditorParity'],
    desktopSource: 'EditorTheme.css, theme.json, BlockNote markdown block rendering',
    mobileFile: 'src/components/workspace/MobileEditorBlocks.tsx',
    surface: 'Read-only editor markdown blocks',
  },
  {
    assertions: ['editor chrome computed styles', 'markdown formatting command user-flow checks', 'raw body-only notes do not synthesize an in-document H1 title'],
    contracts: ['desktopEditorParity', 'desktopPanelParity', 'desktopToolbarParity'],
    desktopSource: 'EditorTheme.css, theme.json, BreadcrumbBar, and BlockNote formatting commands',
    mobileFile: 'src/screens/TabletEditorPanel.tsx',
    surface: 'Tablet editor panel',
  },
  {
    assertions: ['panel widths, swipe gesture checks, click navigation'],
    contracts: ['desktopPanelParity'],
    desktopSource: 'Desktop four-panel workspace shell',
    mobileFile: 'src/screens/TabletWorkspace.tsx',
    surface: 'Tablet workspace shell',
  },
] as const satisfies MobileParityInventoryEntry[]
